// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/vue'

import _post_card from './post-card.bones.json'

registerBones({
  "post-card": _post_card,
})
